"""Add latitude and longitude to LandParcel

Revision ID: 2856d21bf318
Revises: 28a0de40e776
Create Date: 2025-08-14 18:12:57.509755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2856d21bf318'
down_revision: Union[str, Sequence[str], None] = '28a0de40e776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_parcels', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('land_parcels', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land_parcels', 'longitude')
    op.drop_column('land_parcels', 'latitude')
    # ### end Alembic commands ###
